### ISSUE TITLE
Site being blocked due to listing in a spam database

### ISSUE THREAD

**Issue by selangley** [molily/testing-angular#3]
Thanks for you putting this site together.  Last week, it started being blocked at my workplace by the filtering software we use because it's listed in SPAM blacklisting site.

Looks to be this SPAM list:
   dnsbl-3.uceprotect.net

according to:

https://whatismyipaddress.com/blacklist-check

Checking 134.122.88.247 (134.122.88.247). Please wait a minute for the checks to complete.

Blacklist Status

 dnsbl-3.uceprotect.net

Main website:
http://www.uceprotect.net/

**Comment by molily** [comment]
Thanks for letting me know, I will investigate.

The server is a newly-created DigitalOcean Droplet in Europe. As far as I can tell, the server is safe, but there may be several reasons why it’s on a spam list. According to http://www.uceprotect.net/en/rblcheck.php?ipr=134.122.88.247, a whole DigitalOcean subnet is blocked.

![Screen Shot 2021-08-06 at 21 41 12](https://user-images.githubusercontent.com/51251/128563509-ecd4cd13-27ff-4f93-888d-0505345638e7.png)

As a workaround, you can access all content of the book here via GitHub. The chapters are Markdown files with a bit of HTML. For example: https://github.com/molily/testing-angular/blob/main/testing-components.md

The .epub e-book is also available via GitHub: https://github.com/molily/testing-angular/blob/main/assets/testing-angular.epub

**Comment by molily** [comment]
I’m afraid there’s nothing I can do about it except for not hosting the site on DigitalOcean. :/ I’m going to explore alternatives.

If there’s anyone elase who cannot access the site due to this issue, please let me know!
