### ISSUE TITLE
Misc. typos and similar small errors (and Instructions for proofreading)

### ISSUE THREAD

**Issue by datalowe** [molily/testing-angular#5]
Hi, thank you for writing and providing this so-far great book for free :)

I listened to the interview/panel discussion you participated in on [Working Draft](https://workingdraft.de/469/). In it, you mention that you're happy to receive help with proofreading. However, I didn't find any particular suggestions on testing-angular.com itself for how to give proofreading feedback. To me it feels like nitpicking to send an e-mail or open an issue for just a small typo and I'm guessing there are others who would feel the same, so it might help to have particular instructions for how/where to give this type of feedback.

### 1
In [testing principles](https://github.com/molily/testing-angular/blob/main/testing-principles.md#what-makes-a-good-test), there's a sentence:

> Testing tries to nip software problems in **a** bud.

I think this should be:

> Testing tries to nip software problems in **the** bud.

### 2
[Later on in testing principles](https://github.com/molily/testing-angular/blob/main/testing-principles.md#distribution-of-testing-efforts):

> On the other hand, unit test are too low-level to check whether a certain feature works for the user

Should be:
> On the other hand, **unit tests** are...

### 3
In [Angular testing principles](https://github.com/molily/testing-angular/blob/main/angular-testing-principles.md#running-the-unit-and-integration-tests)

> Each .spec.ts file represent a test.

Should be
> Each .spec.ts file **represents** a test.

### 4
[Angular testing principles](https://github.com/molily/testing-angular/blob/main/angular-testing-principles.md#running-the-unit-and-integration-tests)
> In our example application, the CounterService is located in src/app/components/counter/counter.component.ts.

Should be
> In our example application, the **CounterComponent** is located in src/app/components/counter/counter.component.ts.

### 5
[Faking dependencies](https://github.com/molily/testing-angular/blob/main/faking-dependencies.md#spying-on-existing-methods)
```js
spyOn(window, 'fetch');
  .and.returnValue(okResponse);
```
should be
```js

spyOn(window, 'fetch')
  .and.returnValue(okResponse);
```

### 6
[Testing components](https://github.com/molily/testing-angular/blob/main/testing-components.md#testing-helpers)
```js
export function makeClickEvent(
  target: EventTarget
): Partial<MouseEvent> {
  return {
// ...
    target,
    currentTarget: target,
// ...
  };
}
```
Should have `target: target`, rather than just `target`, if I'm not mistaken.

**Comment by molily** [comment]
Thank you very much! Highly appreciated.

> To me it feels like nitpicking to send an e-mail or open an issue for just a small typo and I'm guessing there are others who would feel the same, so it might help to have particular instructions for how/where to give this type of feedback.

A GitHub issue is totally fine, even if it’s just a small typo. I’ll add instructions to the README.

> Should have `target: target`, rather than just `target`, if I'm not mistaken.

Both is possible. `{ target }` is the short version of `{ target: target }`. This is possible [since ECMAScript 2015](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#new_notations_in_ecmascript_2015) and also works in the TypeScript / Angular context.
